### ISSUE TITLE
SM2中有一个关于userid的参数，这个参数能设置么？

### ISSUE THREAD

**Issue by sanderchen** [duanhongyi/gmssl#13]
SM2中有一个关于userid的参数，这个参数能设置么？

**Comment by TheBigFish** [comment]
userid 是可以自行设置的

**Comment by ngmyahoo** [comment]
> userid 是可以自行设置的


请教一下这个userid怎么设置？看了半天没搞懂囧

**Comment by TheBigFish** [comment]
> > userid 是可以自行设置的
> 
> 请教一下这个userid怎么设置？看了半天没搞懂囧

userid 在计算E值时用到，注意前面为 长度 + userid
我提交的 pull requests 增加了E值计算，你可以看一下。

**Comment by ngmyahoo** [comment]
> > > userid 是可以自行设置的
> > 
> > 
> > 请教一下这个userid怎么设置？看了半天没搞懂囧
> 
> userid 在计算E值时用到，注意前面为 长度 + userid
> 我提交的 pull requests 增加了E值计算，你可以看一下。

非常感谢
