### ISSUE TITLE
test_sm3.py

### ISSUE THREAD

**Issue by theThreeKingdom** [duanhongyi/gmssl#3]
where is str_to_list()?

**Comment by DanXL** [comment]
`bytes_to_list ` still failed with error.

**Comment by whyshrha** [comment]
测试sm3  $sm3.sm3_hash('abc') 会报错 AttributeError: 'str' object has no attribute 'append'

**Comment by romanzsh** [comment]
先用bytes.fromhex()，再用func.bytes_to_list，即可。需要先import func

Sent from my iPhone

On May 11, 2020, at 22:15, Haoyu Wu <notifications@github.com> wrote:

﻿

测试sm3 $sm3.sm3_hash('abc') 会报错 AttributeError: 'str' object has no attribute 'append'
