### ISSUE TITLE
sm2 签名是否可以兼容java的bouncycastle 

### ISSUE THREAD

**Issue by cheeseleng** [duanhongyi/gmssl#31]
现在有java实现的sm2加验签，需要用python和它互验，但是观察发现java的签名是144位字符串，python的是128位。
java是用bouncycastle得到的签名，请问python可以兼容吗

**Comment by cheeseleng** [comment]
java进行了asn1的编码，已解决

**Comment by yupk** [comment]
> java进行了asn1的编码，已解决

能否分享解决方法呀

**Comment by peanut-cc** [comment]
> java进行了asn1的编码，已解决

怎么解决的呢？

**Comment by ytt8612** [comment]
python sm2 加密，java的bouncycastle 进行解密是否能兼容，解决方案可以分享一下吗？
