### ISSUE TITLE
SM2加密出来的数据其他工具解不了

### ISSUE THREAD

**Issue by sanderchen** [duanhongyi/gmssl#4]
加密信息：abc
加密后信息：\x16\xfc\xe2<\xd2\xf7 ^\xb7@\xf0#\xa3\x87\xab\xa3\xd2\x18\xe9\xda\x8cJG\xbav;\xdb\xaeeu\xfb:\xcc\x9eT\xd3\xb9\xfc\x0f\x0fH\x8e\xc6'\x7f)\xa8\xab\x92\x82U\xac\x8c\xd2\xae\xf8\x8e@\x16\xea9\xf2\x10\xa4\xb6\xa8,\x90\x92\n\x80\xbb\x9dO\xd0d\t\x97\x10\x18kw.\xd2\xfa,X<\xf9\x9b\x1b\xea_r\xbe\xd4Rp\xa2

这数据是一个怎样数据，我尝试将这数据转换为16进制的数据，然后拿到“SM2算法验证工具”解密，发现解密不了，请问应该如何让其他使用JAVA的服务解密成功呢？

**Comment by duanhongyi** [comment]
java工具通常为base64

**Comment by duanhongyi** [comment]
base64.b64encode

**Comment by duanhongyi** [comment]
用的哪个java包

**Comment by sanderchen** [comment]
是直接使用这个工具https://github.com/zweib730/SM9-misc解密的，用python库加密，加密后的数据base64编码，然后再转16进制，得到的16进制数在传到这个工具尝试解密，但是解密失败，不知道是哪一步出错了

**Comment by duanhongyi** [comment]
> 是直接使用这个工具[https://github.com/zweib730/SM9-misc解密的，用python库加密，加密后的数据base64编码，然后再转16进制，得到的16进制数在传到这个工具尝试解密，但是解密失败，不知道是哪一步出错了](https://github.com/zweib730/SM9-misc%E8%A7%A3%E5%AF%86%E7%9A%84%EF%BC%8C%E7%94%A8python%E5%BA%93%E5%8A%A0%E5%AF%86%EF%BC%8C%E5%8A%A0%E5%AF%86%E5%90%8E%E7%9A%84%E6%95%B0%E6%8D%AEbase64%E7%BC%96%E7%A0%81%EF%BC%8C%E7%84%B6%E5%90%8E%E5%86%8D%E8%BD%AC16%E8%BF%9B%E5%88%B6%EF%BC%8C%E5%BE%97%E5%88%B0%E7%9A%8416%E8%BF%9B%E5%88%B6%E6%95%B0%E5%9C%A8%E4%BC%A0%E5%88%B0%E8%BF%99%E4%B8%AA%E5%B7%A5%E5%85%B7%E5%B0%9D%E8%AF%95%E8%A7%A3%E5%AF%86%EF%BC%8C%E4%BD%86%E6%98%AF%E8%A7%A3%E5%AF%86%E5%A4%B1%E8%B4%A5%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E5%93%AA%E4%B8%80%E6%AD%A5%E5%87%BA%E9%94%99%E4%BA%86)

给我一个java的包，我给你看看。

**Comment by sanderchen** [comment]
是跟我调试的另一方用的是java服务,我这边拿不到他那边的代码,我贴一下我使用gmsll库的python代码
  
    from gmssl import sm2
    import base64
    private_key = '3C2AD19567B69AA3D64D051AD6CD94A8E2BD604933B21E78E63E18461A93FD92'
    public_key = 'F9B6F4D1F95F07DEDD9E182D9506480A7AE4E832BF08A09349420A646BC20A755ADF5B3F041FE664B2B6F32A76C007E961BB0AE06DC51D9DD21F647C39AC3A05'
    sm2_crypt = sm2.CryptSM2(public_key=public_key, private_key=private_key) #初试化SM2算法
    testMsg = b'abc'
    data = sm2_crypt.encrypt(testMsg)  #加密
    print(type(data))
    print(data)

    dataBase64= base64.b64encode(data)
    print(dataBase64)

    dataHex = dataBase64.hex()
    print(dataHex)
   
然后将dataHex这个参数拷贝到https://github.com/zweib730/SM9-misc
这个工具解密,但是解密失败了

**Comment by duanhongyi** [comment]
你要确认你这个工具支持SM2，这个库在我们生产环境中就是和java进行通讯的。

**Comment by sanderchen** [comment]
代码中加密后的data如果要用TCP传输，还需要进行b64encode么？直接进行16进制转换后，是否也可以？

**Comment by sanderchen** [comment]
工具支持SM2的，里面有个“sm2tool_1.exe”文件，可以用来直接加解密，但是我用gmssl python库解不出来……

**Comment by sanderchen** [comment]
你好，能将Python库加密后的数据怎么转换为16进制，并通过TCP传给java的代码举例一下么，谢谢！

**Comment by xinaiwunai** [comment]
我有一个相同的问题。不过我对应的是用微信小程序官方提供的国密包sm-crypto ： https://developers.weixin.qq.com/miniprogram/dev/extended/utils/sm-crypto.html

**Comment by xinaiwunai** [comment]
我已经发现问题了。

微信小程序 sm-crypto 加密后的报文 ms，要转bytes类型，在python 3.5 版本之后，使用
ms = bytes.fromhex(ms) #字符串转hex
然后再使用gmssl提供的 sm2_crypt.decrypt( ) 方法进行解密就可。
ms = sm2_crypt.decrypt(ms) #得到明文，格式为bytes
ms = v2.decode() # bytes转字符串 ，默认使用‘UTF-8’进行编码

**Comment by ytt8612** [comment]
我也遇到同样问题gmsll库的python加密后，解密工具和java sm2 包都无法解密，使用gmsll库的python代码SM2加密，使用java解密的示例可以提供一个么？

**Comment by Miguitian** [comment]
我遇到的问题为使用java进行的sm2的加密，公钥使用的04开头的公钥，但是在使用gmsll和私钥进行解密时，能解密成功，但是无法转化为utf-8编码，但是使用java解密就可以

**Comment by fengjing** [comment]
> 我遇到的问题为使用java进行的sm2的加密，公钥使用的04开头的公钥，但是在使用gmsll和私钥进行解密时，能解密成功，但是无法转化为utf-8编码，但是使用java解密就可以

我也是遇到了同样的问题，python 的sm2 去解密java的东西， 请问 现在解决了吗？
我用了 pk, sk 2个，和 java加密的内容在 https://github.com/44021987/smEncrypt 这个测试 不成功

但是 用 ： https://www.zytool.cn/util/SMUtil  和 https://the-x.cn/zh-cn/cryptography/Sm2.aspx 在线是测试成功的

我也不知道用什么方法解决了

**Comment by fengjing** [comment]
> 我遇到的问题为使用java进行的sm2的加密，公钥使用的04开头的公钥，但是在使用gmsll和私钥进行解密时，能解密成功，但是无法转化为utf-8编码，但是使用java解密就可以

问题解决了
强制 mode=1 
感谢你的 issue 截图，提醒了我

**Comment by Miguitian** [comment]
> > 我遇到的问题为使用java进行的sm2的加密，公钥使用的04开头的公钥，但是在使用gmsll和私钥进行解密时，能解密成功，但是无法转化为utf-8编码，但是使用java解密就可以
> 
> 问题解决了 强制 mode=1 感谢你的 issue 截图，提醒了我

嗯嗯  我那个issue截图目的就是让作者更改一下错误的注视

**Comment by fengjing** [comment]
> > > 我遇到的问题为使用java进行的sm2的加密，公钥使用的04开头的公钥，但是在使用gmsll和私钥进行解密时，能解密成功，但是无法转化为utf-8编码，但是使用java解密就可以
> > 
> > 
> > 问题解决了 强制 mode=1 感谢你的 issue 截图，提醒了我
> 
> 嗯嗯 我那个issue截图目的就是让作者更改一下错误的注视

04开头的要去掉了04
