### ISSUE TITLE
linux env install error

### ISSUE THREAD

**Issue by luckrill** [duanhongyi/gmssl#49]
![image](https://user-images.githubusercontent.com/5372899/166886623-bd7dce39-51b1-4602-899b-a7d7e45fd112.png)

**Comment by peanut-cc** [comment]
pip3 install setuptools

**Comment by peanut-cc** [comment]
> ![image](https://user-images.githubusercontent.com/5372899/166886623-bd7dce39-51b1-4602-899b-a7d7e45fd112.png)

pip3 install setuptools

**Comment by luckrill** [comment]
谢谢
