### ISSUE TITLE
请问16进制的公钥和私钥是怎么产生的

### ISSUE THREAD

**Issue by luohoufu** [duanhongyi/gmssl#7]
请问代码中用的
private_key = '00B9AB0B828FF68872F21A837FC303668428DEA11DCD1B24429D0C99E24EED83D5'
    public_key = 'B9C9A6E04E9C91F7BA880429273747D7EF5DDEB0BB2FF6317EB00BEF331A83081A6994B8993F3F5D6EADDDB81872266C87C018FB4162F5AF347B483E24620207'
是怎么产生的

**Comment by github-amazingboy** [comment]
怎么产生的啊?
