### ISSUE TITLE
兼容python 2嘛？

### ISSUE THREAD

**Issue by forestdew** [duanhongyi/gmssl#8]
大哥，这个是不兼容python 2嘛？

**Comment by duanhongyi** [comment]
是的

**Comment by forestdew** [comment]
大哥啊，这个不兼容python2啊！！！！
python2中的str和bytes是同一个类型的数据。哎....................................................

**Comment by duanhongyi** [comment]
@forestdew python2我个人觉得没有支持的必要了，2.7还有6个月官方都不支持了。

**Comment by forestdew** [comment]
嗯。。。。。。。。。。。。。
大佬，要不你让它支持一下python2,或者你告诉我一下思路，我来改改。
。。。。。。。。。。。。。。。。。。

**Comment by duanhongyi** [comment]
@forestdew 

差别主要在str和bytes上

**Comment by forestdew** [comment]
谢谢您，我找到一个支持python2的版本了

**Comment by forestdew** [comment]
大哥，我又碰到问题了，这个库是只能支持128ASSCII嘛？好像它并不能对汉字进行处理。
谢谢

**Comment by duanhongyi** [comment]
汉字转成bytes

**Comment by LJxFFFF** [comment]
> 谢谢您，我找到一个支持python2的版本了

python2版本能分享一下吗？我目前也遇到这个问题啦
